// <auto-generated />
using System;
using CryptocurrencyAPI.Data.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CryptocurrencyAPI.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20220520201554_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CryptocurrencyAPI.Models.Cryptocurrency", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cryptocurrencies");
                });

            modelBuilder.Entity("CryptocurrencyAPI.Models.CryptocurrencyInformation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CryptocurrencyId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExchangeCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CryptocurrencyId");

                    b.ToTable("CryptocurrencyInformation");
                });

            modelBuilder.Entity("CryptocurrencyAPI.Models.CryptocurrencyInformation", b =>
                {
                    b.HasOne("CryptocurrencyAPI.Models.Cryptocurrency", "Cryptocurrency")
                        .WithMany("CryptocurrencyInformation")
                        .HasForeignKey("CryptocurrencyId");

                    b.Navigation("Cryptocurrency");
                });

            modelBuilder.Entity("CryptocurrencyAPI.Models.Cryptocurrency", b =>
                {
                    b.Navigation("CryptocurrencyInformation");
                });
#pragma warning restore 612, 618
        }
    }
}
